#!/usr/bin/env bash

# git-random
# v1.0.0
# January 10 2023
# https://github.com/olets/git-random
# Copyright (©) 2018-present Henry Bley-Vroman

__git_random_commit() {
	local guid
	local file_path

	# the following is BSD/Mac-friendly
	# the `env LC_CTYPE=C` can be dropped on other systems
	guid=$(env LC_CTYPE=C tr -dc '[:alnum:]' < /dev/urandom | dd bs=4 count=8 2>/dev/null)

	if [[ -z "$guid" ]]; then
		'builtin' 'printf' "git-random: Error generating random string. Exiting\n"
		exit 1
	fi

	file_path="${guid}.txt"

	touch "$file_path"

	'builtin' 'printf' "%s\n" "$guid" >> "$file_path"

	'command' 'git' add "$file_path"

	'builtin' 'printf' "git-random: Adding the line $guid to the file $file_path and committing the change.\n"

	'command' 'git' commit -m "Random commit (${guid})"
}

__git_random_main() {
	local version="1.0.0"
	
	local -i i=
	local -i stash=
	local source_dir

	source_dir=$(dirname -- "${BASH_SOURCE[0]}")

	while (( $# )); do
		case $1 in
			help)
				'command' 'git' random --help 2>/dev/null || 'command' 'man' ${source_dir}/man/man1/git-random.1
				return
				;;
			--version|\
			-v)
				'builtin' 'printf' "%s\n" "$version"
				return
				;;
			-*)
				'builtin' 'printf' "Unsupported option %s\n" "$1"
				return
				;;
			*[!0-9]*)
				# not an integer
				'builtin' 'printf' "Not a valid <count>: %s\n" "$1"
				return
				;;
			*)
				i="$1"
				shift
				break
		esac
	done

	if [[ -n "$*" ]]; then
		'builtin' 'printf' "Too many arguments\n"
		return
	fi

	if (( "$i" < 1 )); then
		i=1
	fi

	if [[ -n $(git diff --cached --name-only) ]]; then
		'builtin' 'printf' "git-random: stashing your staged changes.\n"
		'command' 'git' stash --staged
		'builtin' 'printf' "\n"
		stash=1
	fi

	while (( "$i" > 0 )); do
		__git_random_commit;

		if (( "$i" > 1 )); then
			'builtin' 'printf' "\n"
		fi

		(( i-- ))
	done

	if (( stash )); then
		'builtin' 'printf' "\ngit-random: reinstating stashed staged changes.\n"

		'command' 'git' stash pop --index --quiet

		if (( $? )); then
			'builtin' 'printf' "git-random: There was a problem reinstating restoring your stashed changes. They are in Git's stash{0}.\n"
			return 1
		fi
	fi
}

__git_random_main $*
