#!/usr/bin/env bash

# git-random
# v1.1.0
# June 3 2024
# https://github.com/olets/git-random
# Copyright (©) 2018-present Henry Bley-Vroman

__git_random_commit() {
	local guid
	local file_path

	# the following is BSD/Mac-friendly
	# the `env LC_CTYPE=C` can be dropped on other systems
	guid=$(env LC_CTYPE=C tr -dc '[:alnum:]' < /dev/urandom | dd bs=4 count=8 2>/dev/null)

	[[ -z "$guid" ]] && {
		'builtin' 'printf' "git-random: Error generating random string. Exiting\n"
		exit 1
	}

	file_path="${guid}.txt"

	touch "$file_path"

	'builtin' 'printf' "%s\n" "$guid" >> "$file_path"

	'command' 'git' add "$file_path"

	'builtin' 'printf' "git-random: Adding the line $guid to the file $file_path and committing the change.\n"

	'command' 'git' commit -m "Random commit (${guid})"
}

__git_random_main() {
	local version="1.0.1"
	
	local -i i=
	local -i stash=
	local source_dir

	source_dir=$(dirname -- "${BASH_SOURCE[0]}")

	while (( $# )); do
		case $1 in
			--count=*)
				i="${1:8}"

				(( i )) || {
					'builtin' 'printf' "fatal: count must be greater than or equal to 1\n"
					return
				}

				shift
				;;
			help)
				'command' 'git' random --help 2>/dev/null || 'command' 'man' ${source_dir}/man/man1/git-random.1
				return
				;;
			--version|\
			-v)
				'builtin' 'printf' "%s\n" "$version"
				return
				;;
			-*)
				'builtin' 'printf' "Unsupported option %s\n" "$1"
				return
				;;
			*[!0-9]*)
				# not an integer
				'builtin' 'printf' "Not a valid <count>: %s\n" "$1"
				return
				;;
			*)
				i="$1"
				shift
				break
		esac
	done

	[[ -n "$*" ]] && {
		'builtin' 'printf' "Too many arguments\n"
		return
	}

	(( "$i" < 1 )) && {
		i=1
	}

	[[ -n $(git diff --cached --name-only) ]] && {
		'builtin' 'printf' "git-random: stashing your staged changes.\n"
		'command' 'git' stash --staged
		'builtin' 'printf' "\n"
		stash=1
	}

	while (( "$i" > 0 )); do
		__git_random_commit;

		if (( "$i" > 1 )); then
			'builtin' 'printf' "\n"
		fi

		(( i-- ))
	done

	(( stash )) && {
		'builtin' 'printf' "\ngit-random: applying stashed staged changes.\n"

		'command' 'git' stash pop --index --quiet

		(( $? )) && {
			'builtin' 'printf' "git-random: There was a problem applying stashed staged changes. They are in Git's stash{0}.\n"
			return 1
		}
	}
}

__git_random_main $*
