import { defineConfig } from "vitepress";
import { createTitle, normalize } from "vitepress/dist/client/shared.js";
import markdownItFootnote from "markdown-it-footnote";

const DESCRIPTION = "An aid for learning and experimenting with Git.";
const FALLBACK_META_IMAGE = "git-random-card.png";
const TITLE = "git-random";
const ORIGIN = "https://git-random.olets.dev";

function href(path = "") {
  return new URL(normalize(path), ORIGIN).href;
}

// https://vitepress.dev/reference/site-config
export default defineConfig({
  head: [
    // favicon generated by https://realfavicongenerator.net/
    [
      "link",
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
      },
    ],
    [
      "link",
      {
        rel: "icon",
        type: "image/png",
        sizes: "32x32",
        href: "/favicon-32x32.png",
      },
    ],
    [
      "link",
      {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        href: "/favicon-16x16.png",
      },
    ],
    [
      "link",
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
    ],
    [
      "link",
      {
        rel: "mask-icon",
        href: "/safari-pinned-tab.svg",
        color: "#f05033",
      },
    ],
    [
      "meta",
      {
        name: "msapplication-TileColor",
        content: "#f5f4ed",
      },
    ],
    [
      "meta",
      {
        name: "theme-color",
        content: "#ffffff",
      },
    ],

    // social metas
    ["meta", { property: "og:site_name", content: "git-random" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:image:width", content: "1200" }],
    ["meta", { property: "og:image:height", content: "630" }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],

    // Analytics
    [
      "script",
      {
        src: "https://cdn.usefathom.com/script.js",
        "data-site": "JJWWGCAA",
        "data-spa": "auto",
        defer: "true",
      },
    ],
    [
      "script",
      {
        src: "/js/analytics.js",
      },
    ],

    // Font
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.googleapis.com",
      },
    ],
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.gstatic.com",
        crossorigin: "true",
      },
    ],
    [
      "link",
      {
        href: "https://fonts.googleapis.com/css2?family=Fira+Code&display=swap",
        rel: "stylesheet",
      },
    ],
  ],
  transformPageData(pageData, ctx) {
    let pageDescription = pageData.frontmatter?.description;
    const pageHref = href(pageData.relativePath);
    const pageImage = href(
      pageData.frontmatter?.metaImage ?? FALLBACK_META_IMAGE,
    );
    const pageTitle = createTitle(ctx.siteConfig.site, pageData);

    if (!pageDescription) {
      pageDescription = ctx.siteConfig.site?.description;

      if (pageHref !== href()) {
        pageDescription = [ctx.siteConfig.site?.title, pageDescription]
          .filter((v) => Boolean(v))
          .join(": ");
      }
    }

    pageData.frontmatter.head ??= [];

    pageData.frontmatter.head.push(
      [
        "meta",
        {
          property: "og:image",
          content: pageImage,
        },
      ],
      [
        "meta",
        {
          name: "og:title",
          content: pageTitle,
        },
      ],
      [
        "meta",
        {
          property: "og:url",
          content: pageHref,
        },
      ],
      [
        "meta",
        {
          name: "twitter:image",
          content: pageImage,
        },
      ],
      [
        "meta",
        {
          name: "twitter:title",
          content: pageTitle,
        },
      ],
    );

    if (pageDescription) {
      pageData.frontmatter.head.push(
        [
          "meta",
          {
            name: "og:description",
            content: pageDescription,
          },
        ],
        [
          "meta",
          {
            name: "twitter:description",
            content: pageDescription,
          },
        ],
      );
    }
  },
  title: TITLE,
  description: DESCRIPTION,
  // https://vitepress.dev/reference/site-config#titletemplate
  titleTemplate: `:title :: ${TITLE}`, // to change delimiter from default pipe to play nice with Fathom event id format. see also homepage frontmatter
  // https://vitepress.dev/reference/default-theme-last-updated
  lastUpdated: true,
  markdown: {
    externalLinks: {
      class: "vp-external-link-icon",
      target: "_self",
    },
    config: (md) => {
      md.use(markdownItFootnote);
    },
    theme: {
      light: "github-light-high-contrast",
      dark: "github-dark-high-contrast",
    },
  },
  srcExclude: ["vitepressignore"],
  sitemap: {
    hostname: href(),
  },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config

    editLink: {
      pattern: "https://github.com/olets/git-random/edit/main/docs/:path",
    },

    logo: "/images/git-random-logo.png",

    nav: [
      {
        text: "Source, Changelog, License",
        link: "https://github.com/olets/git-random/",
        target: "_self",
      },
      {
        text: "olets.dev",
        link: "https://olets.dev",
        target: "_self",
      },
    ],

    search: {
      provider: "local",
    },

    sidebar: [
      { text: "Overview", link: "/" },
      { text: "Installation", link: "/installation" },
      { text: "Usage", link: "/usage" },
      { text: "Options", link: "/options" },
      {
        text: "Examples",
        items: [
          {
            text: "Practice rebasing",
            link: "/examples/practice-rebasing",
          },
          {
            text: "Practice conflict resolution",
            link: "/examples/practice-conflict-resolution",
          },
          {
            text: "Follow along with Git's docs",
            link: "/examples/follow-along-with-gits-docs",
          },
        ],
      },
      { text: "Contributing", link: "/contributing" },
      { text: "Acknowledgments", link: "/acknowledgments" },
    ],
  },
});
